name: Terraform Deploy (Single Code, Dynamic Inputs)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - production

      region:
        description: "Select Azure Region"
        required: true
        default: eastus
        type: choice
        options:
          - eastus
          - westeurope
          - centralus

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./envs

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./envs

      - name: Terraform Plan
        run: terraform plan -input=false -var="environment=${{ github.event.inputs.environment }}" -var="location=${{ github.event.inputs.region }}"
        working-directory: ./envs

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -var="environment=${{ github.event.inputs.environment }}" -var="location=${{ github.event.inputs.region }}"
        working-directory: ./envs
